name: Build and deploy to e2e on push

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [labeled]

jobs:
  dispatch-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      - name: Check if added label is "🔒 Keep e2e"
        env:
            GH_TOKEN: ${{ github.token }}
        id: label_check
        run: |
          labels=$(gh pr view ${{ steps.PR.outputs.number }} --repo ${{ github.repository }} --json labels | jq '.labels')
          if [[ "$labels" != *"🔒 Keep e2e"* ]]; then
            echo "Label not found or incorrect, skipping dispatch."
            echo keep_e2e=false >> $GITHUB_ENV
          else
            echo "Correct label added, dispatching deploy workflow."
            echo keep_e2e=true >> $GITHUB_ENV
          fi
      - if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo "Running deployment"
          echo ${{steps.PR.outputs.pr_found}}
          echo ${{env.keep_e2e}}
