name: Build and deploy to e2e on push

on:
  push:
    branches: [ "*" ]
  pull_request:
    types:
        - labeled
        - opened

jobs:
  dispatch-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Get PR labels on push event
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        if: github.event_name == 'push'
        id: PR_push

      - name: Get PR labels on pull_request event
        id: PR_pull
        if: github.event_name == 'pull_request'
        run: |
            pr_number=${{ github.event.pull_request.number }}
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}")
            labels=$(echo "$response" | jq '.labels | map(.name) | join(",")')
            echo pr_labels=$labels
            echo pr_labels=$labels >> $GITHUB_OUTPUT

      - name: Check if added label is "🔒 Keep e2e"
        id: label_check
        run: |
          [[ ${{github.event_name}} == 'pull_request' ]] && \
           labels="${{ steps.PR_pull.outputs.pr_labels }}" || \
           labels="${{ steps.PR_push.outputs.pr_labels }}"
          echo $labels
          if [[ "${labels}" != *"🔒 Keep e2e"* ]]; then
            echo "Label not found or incorrect, skipping dispatch."
            echo keep_e2e=false >> $GITHUB_ENV
          else
            echo "Correct label added, dispatching deploy workflow."
            echo keep_e2e=true >> $GITHUB_ENV
          fi
      - if: steps.PR_push.outputs.pr_found == 'true' && github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
            echo "Running deployment"
            echo ${{github.event_name}}
            echo ${{env.keep_e2e}}
  

