name: Build and deploy to e2e on push

on:
  push:
    branches: [ "*" ]
  pull_request:
    types:
        - labeled
        - opened

jobs:
  dispatch-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Get PR details on push event
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        if: github.event_name == 'push'
        id: PR

      - name: Check if added label is "🔒 Keep e2e"
        id: label_check
        run: |
          [[ ${{github.event_name}} == 'pull_request' ]] && \
           labels="$(jq -r '.label.name' "$GITHUB_EVENT_PATH")" || \
           labels="${{ steps.PR.outputs.pr_labels }}"
          cat $GITHUB_EVENT_PATH
          echo $labels
          if [[ "${labels}" != *"🔒 Keep e2e"* ]]; then
            echo "Label not found or incorrect, skipping dispatch."
            echo keep_e2e=false >> $GITHUB_ENV
          else
            echo "Correct label added, dispatching deploy workflow."
            echo keep_e2e=true >> $GITHUB_ENV
          fi
      - if: (steps.PR.outputs.pr_found == 'true' && github.event_name == 'push') || github.event_name == 'pull_request'
        run: |
          echo "Running deployment"
          echo ${{steps.PR.outputs.pr_found}}
          echo ${{github.event_name}}
          echo ${{env.keep_e2e}}

