name: Build and deploy to e2e on push

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [labeled]

jobs:
  dispatch-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outputs.pr_found == 'true'
        env:
          # JSON object with the full PR object
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
      - name: Check if added label is "🔒 Keep e2e"
        env:
            GH_TOKEN: ${{ github.token }}
        id: label_check
        run: |
          labels=$(gh pr view ${{ steps.PR.outputs.number }} --repo ${{ github.repository }} --json labels | jq '.labels')
          
          if [[ "$added_label" != *"🔒 Keep e2e"* ]]; then
            echo "Label not found or incorrect, skipping dispatch."
            echo keep_e2e=false >> $GITHUB_ENV
          else
            echo "Correct label added, dispatching deploy workflow."
            echo keep_e2e=true >> $GITHUB_ENV
          fi
      - run: |
          echo "Running deployment"
          echo "$GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
          echo ${{steps.PR.outputs.pr_found}}
          echo ${{env.keep_e2e}}
